/* Nombre de la clase                : CBuscaCuadros 
 * Descripción de la clase        : Clase para la consulta de los cuadros
 * Fecha de creación                 : 15/04/2016 
 * Elaboró                                     : Nava Ramirez Luis Fernando 
 * Fecha de Liberación              : - 
 * Autorizó  : -
 * Fecha Mantenimiento           : 
 * Folio mantenimiento             : 
 * Descripción del mantto       :
 * Responsable                          :  
 * Revisor                                    : 
 */
package bfx.cuadros;

import bfx.controladores.CManipulaDB;
import bfx.controladores.CPanelFondo;
import java.sql.Connection;

/**
 * Interfaz gráfica de usuario para consultar un Cuadro
 * @author Techno Engineers
 * @version 1.0
 */
public class CBuscaCuadros extends javax.swing.JFrame {

    private CPanelFondo fondo;

    /**
     * Creates new form VtnA
     */
    public CBuscaCuadros() {
        initComponents();
        this.setLayout(null);
        this.setLocationRelativeTo(null);
        fondo = new CPanelFondo("Busqueda General Cuadros ...", "../imagenes/ballet.png", 0, 0, 420, 380);
        this.add(fondo);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        informacion = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Altas de ...");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        informacion.setColumns(20);
        informacion.setRows(5);
        jScrollPane1.setViewportView(informacion);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        Connection lCNConexion = CManipulaDB.cmetpbConectaDB();
        informacion.setText(CManipulaDB.cmetpbSConsultaCuadros(CManipulaDB.cmetpbCargaCuadros(CManipulaDB.cmetpbALConsult(lCNConexion, "cuadros", "*", ""))));
        CManipulaDB.cmetpbDesconectaDB(lCNConexion);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea informacion;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
