/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bfx.inicio;

import bfx.adeudos.CAgregarAdeudos;
import bfx.adeudos.CPagoAdeudos;
import bfx.clases.CDanios;
import bfx.vestuarios.*;
import bfx.controladores.CConexion;
import bfx.controladores.CMensajes;
import bfx.controladores.CPanelFondo;
import bfx.controladores.CQuerys;
import bfx.cuadros.CBuscaBailes;
import bfx.cuadros.CBuscaCuadros;
import bfx.cuadros.CBuscaRegiones;
import bfx.cuadros.CEliminaBailes;
import bfx.cuadros.CEliminaRegiones;
import bfx.cuadros.CModificaBailes;
import bfx.cuadros.CModificaRegiones;
import bfx.danios.CAltaDanios;
import bfx.danios.CConsultaDanios;
import bfx.cuadros.CAltaBailes;
import bfx.cuadros.CAltaRegiones;
import bfx.rentas.CAltaRentasParametros;
import bfx.rentas.CConsultaRentasParametros;
import bfx.rentas.CModificaRentasParametros;
import bfx.usuarios.CConsultaUsuarios;
import bfx.usuarios.CRegistrarUsuarios;
import java.awt.Image;
import java.sql.Connection;
import java.util.ArrayList;
import javax.swing.ImageIcon;

/**
 *
 * @author Mauro
 */
public class VtnP extends javax.swing.JFrame
{

    CPanelFondo objCPanelFondo;
    ImageIcon objImageIcon = new ImageIcon(getClass().getResource("../imagenes/ico.png"));
    Image objImage = objImageIcon.getImage();

    /**
     * Creates new form VtnP
     */
    public VtnP()
    {
        initComponents();
        this.setLayout(null);
        this.setLocationRelativeTo(null);
        objCPanelFondo = new CPanelFondo("Ventana Principal" , "../imagenes/background.png" , 0 , 0 , 1365 , 728);
        this.setSize(1365,728);
        this.add(objCPanelFondo);
        this.pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jMenuBar1 = new javax.swing.JMenuBar();
        objMdanios = new javax.swing.JMenu();
        objMIaltaDanios = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        objMIconsultarDanios = new javax.swing.JMenuItem();
        objMvestuarioInventario = new javax.swing.JMenu();
        objMIaltaVestuarioInventario = new javax.swing.JMenuItem();
        objMIconsultarVestuarioInventario = new javax.swing.JMenuItem();
        objMrentas = new javax.swing.JMenu();
        objMIaltaRentas = new javax.swing.JMenuItem();
        objMIconsultarRentas = new javax.swing.JMenuItem();
        objMImodificarRentas = new javax.swing.JMenuItem();
        objMcuadros = new javax.swing.JMenu();
        objMIaltaRegiones = new javax.swing.JMenuItem();
        objMIaltabailes = new javax.swing.JMenuItem();
        objMIconsultarCuadros = new javax.swing.JMenuItem();
        objMIconsultarRegiones = new javax.swing.JMenuItem();
        objMIconsultarBailes = new javax.swing.JMenuItem();
        objMImodificarRegiones = new javax.swing.JMenuItem();
        objMImodificarBailes = new javax.swing.JMenuItem();
        objMIeliminarRegiones = new javax.swing.JMenuItem();
        objMIeliminarBailes = new javax.swing.JMenuItem();
        objMusuarios = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        objMadeudos = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BFX - Ballet Folclórico Xinantécatl");
        setBackground(new java.awt.Color(255, 255, 102));
        setMinimumSize(new java.awt.Dimension(1365, 728));
        setResizable(false);

        objMdanios.setText("Daños");

        objMIaltaDanios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        objMIaltaDanios.setText("Altas");
        objMIaltaDanios.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                objMIaltaDaniosActionPerformed(evt);
            }
        });
        objMdanios.add(objMIaltaDanios);
        objMdanios.add(jSeparator1);

        objMIconsultarDanios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        objMIconsultarDanios.setText("Consultas");
        objMIconsultarDanios.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                objMIconsultarDaniosActionPerformed(evt);
            }
        });
        objMdanios.add(objMIconsultarDanios);

        jMenuBar1.add(objMdanios);

        objMvestuarioInventario.setText("Vestuarios e Inventarios");

        objMIaltaVestuarioInventario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        objMIaltaVestuarioInventario.setText("Alta de vestuario e inventario");
        objMIaltaVestuarioInventario.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                objMIaltaVestuarioInventarioActionPerformed(evt);
            }
        });
        objMvestuarioInventario.add(objMIaltaVestuarioInventario);

        objMIconsultarVestuarioInventario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        objMIconsultarVestuarioInventario.setText("Consulta de vestuario e inventario");
        objMIconsultarVestuarioInventario.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                objMIconsultarVestuarioInventarioActionPerformed(evt);
            }
        });
        objMvestuarioInventario.add(objMIconsultarVestuarioInventario);

        jMenuBar1.add(objMvestuarioInventario);

        objMrentas.setText("Rentas");
        objMrentas.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                objMrentasActionPerformed(evt);
            }
        });

        objMIaltaRentas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        objMIaltaRentas.setText("Alta de rentas");
        objMIaltaRentas.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                objMIaltaRentasActionPerformed(evt);
            }
        });
        objMrentas.add(objMIaltaRentas);

        objMIconsultarRentas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        objMIconsultarRentas.setText("Consultar de rentas");
        objMIconsultarRentas.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                objMIconsultarRentasActionPerformed(evt);
            }
        });
        objMrentas.add(objMIconsultarRentas);

        objMImodificarRentas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        objMImodificarRentas.setText("Modificar rentas");
        objMImodificarRentas.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                objMImodificarRentasActionPerformed(evt);
            }
        });
        objMrentas.add(objMImodificarRentas);

        jMenuBar1.add(objMrentas);

        objMcuadros.setText("Cuadros");

        objMIaltaRegiones.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        objMIaltaRegiones.setText("Alta de regiones");
        objMIaltaRegiones.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                objMIaltaRegionesActionPerformed(evt);
            }
        });
        objMcuadros.add(objMIaltaRegiones);

        objMIaltabailes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK));
        objMIaltabailes.setText("Alta de bailes");
        objMIaltabailes.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                objMIaltabailesActionPerformed(evt);
            }
        });
        objMcuadros.add(objMIaltabailes);

        objMIconsultarCuadros.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        objMIconsultarCuadros.setText("Consultar cuadros");
        objMIconsultarCuadros.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                objMIconsultarCuadrosActionPerformed(evt);
            }
        });
        objMcuadros.add(objMIconsultarCuadros);

        objMIconsultarRegiones.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        objMIconsultarRegiones.setText("Consultar regiones");
        objMIconsultarRegiones.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                objMIconsultarRegionesActionPerformed(evt);
            }
        });
        objMcuadros.add(objMIconsultarRegiones);

        objMIconsultarBailes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK));
        objMIconsultarBailes.setText("Consultar bailes");
        objMIconsultarBailes.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                objMIconsultarBailesActionPerformed(evt);
            }
        });
        objMcuadros.add(objMIconsultarBailes);

        objMImodificarRegiones.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        objMImodificarRegiones.setText("Modificar regiones");
        objMImodificarRegiones.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                objMImodificarRegionesActionPerformed(evt);
            }
        });
        objMcuadros.add(objMImodificarRegiones);

        objMImodificarBailes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.ALT_MASK));
        objMImodificarBailes.setText("Modificar bailes");
        objMImodificarBailes.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                objMImodificarBailesActionPerformed(evt);
            }
        });
        objMcuadros.add(objMImodificarBailes);

        objMIeliminarRegiones.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        objMIeliminarRegiones.setText("Eliminar regiones");
        objMIeliminarRegiones.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                objMIeliminarRegionesActionPerformed(evt);
            }
        });
        objMcuadros.add(objMIeliminarRegiones);

        objMIeliminarBailes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK));
        objMIeliminarBailes.setText("Eliminar bailes");
        objMIeliminarBailes.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                objMIeliminarBailesActionPerformed(evt);
            }
        });
        objMcuadros.add(objMIeliminarBailes);

        jMenuBar1.add(objMcuadros);

        objMusuarios.setText("Usuarios");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Altas");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItem1ActionPerformed(evt);
            }
        });
        objMusuarios.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Consultas");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItem2ActionPerformed(evt);
            }
        });
        objMusuarios.add(jMenuItem2);

        jMenuBar1.add(objMusuarios);

        objMadeudos.setText("Adeudos");

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Altas");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItem3ActionPerformed(evt);
            }
        });
        objMadeudos.add(jMenuItem3);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setText("Pagos");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItem4ActionPerformed(evt);
            }
        });
        objMadeudos.add(jMenuItem4);

        jMenuBar1.add(objMadeudos);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void objMIaltaDaniosActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_objMIaltaDaniosActionPerformed
    {//GEN-HEADEREND:event_objMIaltaDaniosActionPerformed
        CAltaDanios objCAltaDanios = new CAltaDanios();
        objCAltaDanios.setLocationRelativeTo(null);
        objCAltaDanios.setVisible(true);
        objCAltaDanios.setIconImage(objImage);
        objCAltaDanios.setSize(569 , 333);
    }//GEN-LAST:event_objMIaltaDaniosActionPerformed

    private void objMIconsultarDaniosActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_objMIconsultarDaniosActionPerformed
    {//GEN-HEADEREND:event_objMIconsultarDaniosActionPerformed

        CDanios objCDanios = new CDanios();
        ArrayList<Object> lALBandera = objCDanios.objCQuerys.metpbALSeleccion(objCDanios.objConnection, "*", "danio", "");
        if (lALBandera.get(0).toString().trim().equals(""))
        {
            CMensajes.cmetpbFalla(this, "No hay registros de daños, verifique por favor");
        } else
        {
            CConsultaDanios objCConsultaDanios = new CConsultaDanios();
            objCConsultaDanios.setLocationRelativeTo(null);
            objCConsultaDanios.setVisible(true);
            objCConsultaDanios.setIconImage(objImage);
            objCConsultaDanios.setSize(780 , 485);
        }

    }//GEN-LAST:event_objMIconsultarDaniosActionPerformed

    private void objMIaltaVestuarioInventarioActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_objMIaltaVestuarioInventarioActionPerformed
    {//GEN-HEADEREND:event_objMIaltaVestuarioInventarioActionPerformed
        new CAltaVestuarios().setVisible(true);
    }//GEN-LAST:event_objMIaltaVestuarioInventarioActionPerformed

    private void objMIconsultarVestuarioInventarioActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_objMIconsultarVestuarioInventarioActionPerformed
    {//GEN-HEADEREND:event_objMIconsultarVestuarioInventarioActionPerformed
        new CConsultaVestuarios().setVisible(true);
    }//GEN-LAST:event_objMIconsultarVestuarioInventarioActionPerformed

    private void objMrentasActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_objMrentasActionPerformed
    {//GEN-HEADEREND:event_objMrentasActionPerformed
       
    }//GEN-LAST:event_objMrentasActionPerformed

    private void objMIaltaRentasActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_objMIaltaRentasActionPerformed
    {//GEN-HEADEREND:event_objMIaltaRentasActionPerformed
       new CAltaRentasParametros().setVisible(true);
    }//GEN-LAST:event_objMIaltaRentasActionPerformed

    private void objMIconsultarRentasActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_objMIconsultarRentasActionPerformed
    {//GEN-HEADEREND:event_objMIconsultarRentasActionPerformed
        new CConsultaRentasParametros().setVisible(true);
    }//GEN-LAST:event_objMIconsultarRentasActionPerformed

    private void objMImodificarRentasActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_objMImodificarRentasActionPerformed
    {//GEN-HEADEREND:event_objMImodificarRentasActionPerformed
        new CModificaRentasParametros().setVisible(true);
    }//GEN-LAST:event_objMImodificarRentasActionPerformed

    private void objMIaltaRegionesActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_objMIaltaRegionesActionPerformed
    {//GEN-HEADEREND:event_objMIaltaRegionesActionPerformed
        CAltaRegiones objCAltaRegiones = new CAltaRegiones();
        objCAltaRegiones.setVisible(true);
        objCAltaRegiones.setIconImage(objImage);
    }//GEN-LAST:event_objMIaltaRegionesActionPerformed

    private void objMIaltabailesActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_objMIaltabailesActionPerformed
    {//GEN-HEADEREND:event_objMIaltabailesActionPerformed
        CAltaBailes objAltaBailes = new CAltaBailes();
        objAltaBailes.setVisible(true);
        objAltaBailes.setIconImage(objImage);
    }//GEN-LAST:event_objMIaltabailesActionPerformed

    private void objMIconsultarCuadrosActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_objMIconsultarCuadrosActionPerformed
    {//GEN-HEADEREND:event_objMIconsultarCuadrosActionPerformed
        CBuscaCuadros objCBuscaCuadros = new CBuscaCuadros();
        objCBuscaCuadros.setVisible(true);
        objCBuscaCuadros.setIconImage(objImage);
    }//GEN-LAST:event_objMIconsultarCuadrosActionPerformed

    private void objMIconsultarRegionesActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_objMIconsultarRegionesActionPerformed
    {//GEN-HEADEREND:event_objMIconsultarRegionesActionPerformed
        CBuscaRegiones objCBuscaRegiones = new CBuscaRegiones();
        objCBuscaRegiones.setVisible(true);
        objCBuscaRegiones.setIconImage(objImage);
    }//GEN-LAST:event_objMIconsultarRegionesActionPerformed

    private void objMIconsultarBailesActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_objMIconsultarBailesActionPerformed
    {//GEN-HEADEREND:event_objMIconsultarBailesActionPerformed
        CBuscaBailes objCBuscaBailes = new CBuscaBailes();
        objCBuscaBailes.setVisible(true);
        objCBuscaBailes.setIconImage(objImage);
    }//GEN-LAST:event_objMIconsultarBailesActionPerformed

    private void objMImodificarRegionesActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_objMImodificarRegionesActionPerformed
    {//GEN-HEADEREND:event_objMImodificarRegionesActionPerformed
        CModificaRegiones objCModificaRegiones = new CModificaRegiones();
        objCModificaRegiones.setVisible(true);
        objCModificaRegiones.setIconImage(objImage);
    }//GEN-LAST:event_objMImodificarRegionesActionPerformed

    private void objMImodificarBailesActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_objMImodificarBailesActionPerformed
    {//GEN-HEADEREND:event_objMImodificarBailesActionPerformed
        CModificaBailes objCModificaBailes = new CModificaBailes();
        objCModificaBailes.setVisible(true);
        objCModificaBailes.setIconImage(objImage);
    }//GEN-LAST:event_objMImodificarBailesActionPerformed

    private void objMIeliminarRegionesActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_objMIeliminarRegionesActionPerformed
    {//GEN-HEADEREND:event_objMIeliminarRegionesActionPerformed
        CEliminaRegiones objCEliminaRegiones = new CEliminaRegiones();
        objCEliminaRegiones.setVisible(true);
        objCEliminaRegiones.setIconImage(objImage);
    }//GEN-LAST:event_objMIeliminarRegionesActionPerformed

    private void objMIeliminarBailesActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_objMIeliminarBailesActionPerformed
    {//GEN-HEADEREND:event_objMIeliminarBailesActionPerformed
        CEliminaBailes objCEliminaBailes = new CEliminaBailes();
        objCEliminaBailes.setVisible(true);
        objCEliminaBailes.setIconImage(objImage);
    }//GEN-LAST:event_objMIeliminarBailesActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem1ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem1ActionPerformed
        CRegistrarUsuarios objCRegistrarUsuarios1=new CRegistrarUsuarios();
        objCRegistrarUsuarios1.setVisible(true);
        objCRegistrarUsuarios1.setLocationRelativeTo(null);
        objCRegistrarUsuarios1.setIconImage(objImage);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem2ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem2ActionPerformed
        CConsultaUsuarios objCConsultaUsuarios1=new CConsultaUsuarios();
        objCConsultaUsuarios1.setVisible(true);
        objCConsultaUsuarios1.setLocationRelativeTo(null);
        objCConsultaUsuarios1.setIconImage(objImage);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem3ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem3ActionPerformed
        CAgregarAdeudos objCConsultaUsuarios1=new CAgregarAdeudos();
        objCConsultaUsuarios1.setVisible(true);
        objCConsultaUsuarios1.setLocationRelativeTo(null);
//        objCConsultaUsuarios1.setIconImage(objImage);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem4ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem4ActionPerformed
        CPagoAdeudos objCConsultaUsuarios1=new CPagoAdeudos();
        objCConsultaUsuarios1.setVisible(true);
        objCConsultaUsuarios1.setLocationRelativeTo(null);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(VtnP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(VtnP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(VtnP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(VtnP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                VtnP objVtnP = new VtnP();
                objVtnP.setVisible(true);
                ImageIcon objImageIcon = new ImageIcon(getClass().getResource("../imagenes/ico.png"));
                Image objImage = objImageIcon.getImage();
                objVtnP.setIconImage(objImage);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem objMIaltaDanios;
    private javax.swing.JMenuItem objMIaltaRegiones;
    private javax.swing.JMenuItem objMIaltaRentas;
    private javax.swing.JMenuItem objMIaltaVestuarioInventario;
    private javax.swing.JMenuItem objMIaltabailes;
    private javax.swing.JMenuItem objMIconsultarBailes;
    private javax.swing.JMenuItem objMIconsultarCuadros;
    private javax.swing.JMenuItem objMIconsultarDanios;
    private javax.swing.JMenuItem objMIconsultarRegiones;
    private javax.swing.JMenuItem objMIconsultarRentas;
    private javax.swing.JMenuItem objMIconsultarVestuarioInventario;
    private javax.swing.JMenuItem objMIeliminarBailes;
    private javax.swing.JMenuItem objMIeliminarRegiones;
    private javax.swing.JMenuItem objMImodificarBailes;
    private javax.swing.JMenuItem objMImodificarRegiones;
    private javax.swing.JMenuItem objMImodificarRentas;
    private javax.swing.JMenu objMadeudos;
    private javax.swing.JMenu objMcuadros;
    private javax.swing.JMenu objMdanios;
    private javax.swing.JMenu objMrentas;
    private javax.swing.JMenu objMusuarios;
    private javax.swing.JMenu objMvestuarioInventario;
    // End of variables declaration//GEN-END:variables
}
